// Copyright (c) 2023 -  Restate Software, Inc., Restate GmbH.
// All rights reserved.
//
// Use of this software is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0.

//! Implementation of the declarative `service!` / `object!` / `workflow!` item macros.
//!
//! `service!(Greeter: { greet, other })` defines a zero-sized `Greeter` service type (implementing
//! the runtime `Service`/`Discoverable` traits by dispatching to the listed [`macro@crate::handler`]
//! values) plus a `GreeterClient`, from a single declaration — no runtime builder call.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::parse::{Parse, ParseStream};
use syn::punctuated::Punctuated;
use syn::{Error, Ident, LitStr, Token, braced};

#[derive(Clone, Copy)]
pub(crate) enum Kind {
    Service,
    Object,
    Workflow,
}

/// Parsed `Name: { handler, handler, ... }`.
struct ServiceDef {
    name: Ident,
    handlers: Vec<Ident>,
}

impl Parse for ServiceDef {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let name: Ident = input.parse()?;
        input.parse::<Token![:]>()?;

        let content;
        braced!(content in input);
        let handlers: Punctuated<Ident, Token![,]> =
            content.parse_terminated(Ident::parse, Token![,])?;

        // Reserve the syntax for future extension (service-level `options: { .. }`,
        // per-handler config blocks, an explicit wire-name, ...).
        if !input.is_empty() {
            return Err(Error::new(
                input.span(),
                "only `Name: { handler, ... }` is supported for now; \
                 per-handler config and service options are not yet available in the macro \
                 (use `.with_options(..)` on the generated type for options)",
            ));
        }

        Ok(ServiceDef {
            name,
            handlers: handlers.into_iter().collect(),
        })
    }
}

pub(crate) fn expand(kind: Kind, input: TokenStream) -> syn::Result<TokenStream> {
    let def: ServiceDef = syn::parse2(input)?;
    let name = &def.name;
    let handlers = &def.handlers;
    let name_str = LitStr::new(&name.to_string(), name.span());
    let client_ident = format_ident!("{}Client", name);

    let kind_path = match kind {
        Kind::Service => quote!(::restate_sdk::service::ServiceKind),
        Kind::Object => quote!(::restate_sdk::service::ObjectKind),
        Kind::Workflow => quote!(::restate_sdk::service::WorkflowKind),
    };
    let service_type = match kind {
        Kind::Service => quote!(::restate_sdk::discovery::ServiceType::Service),
        Kind::Object => quote!(::restate_sdk::discovery::ServiceType::VirtualObject),
        Kind::Workflow => quote!(::restate_sdk::discovery::ServiceType::Workflow),
    };

    // Server: dispatch each invocation to the matching handler ZST.
    // `<#h as Handler<#kind_path>>` also enforces that every listed handler is of the right kind.
    let dispatch_arms = handlers.iter().map(|h| {
        quote! {
            if __handler == #h::NAME {
                return <#h as ::restate_sdk::service::Handler<#kind_path>>::handle(&#h, ctx);
            }
        }
    });
    let handler_metas = handlers
        .iter()
        .map(|h| quote!(<#h as ::restate_sdk::service::Handler<#kind_path>>::meta(&#h)));

    // Client (same shape as the one generated by `interface!`), typed from the handlers' associated
    // input/output types, and targeting each handler's real wire name (`#h::NAME`).
    let (key_field, into_client_impl) = match kind {
        Kind::Service => (
            quote!(),
            quote! {
                impl<'ctx> ::restate_sdk::context::IntoServiceClient<'ctx> for #client_ident<'ctx> {
                    fn create_client(ctx: &'ctx ::restate_sdk::endpoint::ContextInternal) -> Self {
                        Self { ctx }
                    }
                }
            },
        ),
        Kind::Object => (
            quote!(key: String,),
            quote! {
                impl<'ctx> ::restate_sdk::context::IntoObjectClient<'ctx> for #client_ident<'ctx> {
                    fn create_client(ctx: &'ctx ::restate_sdk::endpoint::ContextInternal, key: String) -> Self {
                        Self { ctx, key }
                    }
                }
            },
        ),
        Kind::Workflow => (
            quote!(key: String,),
            quote! {
                impl<'ctx> ::restate_sdk::context::IntoWorkflowClient<'ctx> for #client_ident<'ctx> {
                    fn create_client(ctx: &'ctx ::restate_sdk::endpoint::ContextInternal, key: String) -> Self {
                        Self { ctx, key }
                    }
                }
            },
        ),
    };
    let client_methods = handlers.iter().map(|h| {
        let target = match kind {
            Kind::Service => quote!(::restate_sdk::context::RequestTarget::service(#name_str, #h::NAME)),
            Kind::Object => {
                quote!(::restate_sdk::context::RequestTarget::object(#name_str, &self.key, #h::NAME))
            }
            Kind::Workflow => {
                quote!(::restate_sdk::context::RequestTarget::workflow(#name_str, &self.key, #h::NAME))
            }
        };
        quote! {
            pub fn #h(
                &self,
                req: <#h as ::restate_sdk::service::TypedHandler<#kind_path>>::Input,
            ) -> ::restate_sdk::context::Request<
                'ctx,
                <#h as ::restate_sdk::service::TypedHandler<#kind_path>>::Input,
                <#h as ::restate_sdk::service::TypedHandler<#kind_path>>::Output,
            > {
                self.ctx.request(#target, req)
            }
        }
    });

    let svc_doc = format!(
        "The `{name}` service definition. Bind it with `Endpoint::builder().bind({name})`, \
         or `{name}.with_options(..)` to attach options."
    );
    let client_doc = format!("Client to invoke the `{name}` service from another handler.");

    Ok(quote! {
        #[doc = #svc_doc]
        #[derive(::core::clone::Clone, ::core::marker::Copy)]
        pub struct #name;

        impl ::restate_sdk::service::Service for #name {
            type Future = ::restate_sdk::service::ServiceBoxFuture;

            fn handle(
                &self,
                ctx: ::restate_sdk::endpoint::ContextInternal,
            ) -> Self::Future {
                let __handler = ::restate_sdk::endpoint::ContextInternal::handler_name(&ctx).to_owned();
                #( #dispatch_arms )*
                let __err = ::restate_sdk::endpoint::Error::unknown_handler(
                    ctx.service_name(),
                    ctx.handler_name(),
                );
                ::std::boxed::Box::pin(async move { ::core::result::Result::Err(__err) })
            }
        }

        impl ::restate_sdk::service::Discoverable for #name {
            fn discover() -> ::restate_sdk::discovery::Service {
                ::restate_sdk::service::build_discovery(
                    #name_str,
                    #service_type,
                    ::std::vec![ #( #handler_metas ),* ],
                )
            }
        }

        impl #name {
            /// Attach [`ServiceOptions`](restate_sdk::endpoint::ServiceOptions), producing a bindable
            /// [`ServiceDefinition`](restate_sdk::service::ServiceDefinition).
            pub fn with_options(
                self,
                options: ::restate_sdk::endpoint::ServiceOptions,
            ) -> ::restate_sdk::service::ServiceDefinition {
                ::restate_sdk::service::ServiceDefinition::from_service_with_options(self, options)
            }
        }

        #[doc = #client_doc]
        pub struct #client_ident<'ctx> {
            ctx: &'ctx ::restate_sdk::endpoint::ContextInternal,
            #key_field
        }

        #into_client_impl

        impl<'ctx> #client_ident<'ctx> {
            #( #client_methods )*
        }
    })
}
